runtime: nodejs
env: flex

env_variables:
  DATABASEURL: 'mongodb+srv://root:cfQQ9M-d-DJbQRi.ziG.@cluster0-jnr7d.gcp.mongodb.net/test?retryWrites=true&w=majority'
  CLOUDINARY_URL: 'cloudinary://329144582698313:DeztX2WIwRFw6qtP5CUrpdBIq9s@dhivb8oa7'
  CLOUDINARY_API_KEY: '329144582698313'
  CLOUDINARY_API_SECRETE: 'DeztX2WIwRFw6qtP5CUrpdBIq9s'
  GEOCODER_API_KEY: 'AIzaSyAEzUBf9IYGQkH-ztiVV7s7U0zpM1a0HDE'